//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARAFON
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public string Email = null;
        public string Password = null;
        public string FirstName = null;
        public string LastName = null;
        public string RoleId = null;
        public string Login = null;
        public virtual Role Role { get; set; }
    }
}
