//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARAFON
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public bool checkIsRegisterOnMarafon = false;
        public int AgeGroup = 0;
        public int RunnerId = 0;
        public DateTime DateOfBirth = new DateTime();
        public string Gender = null;
        public string CountryCode = null;
        public string Email = null;
        public string Password = null;
        public string FirstName = null;
        public string LastName = null;
        public string RoleId = null;
        public string Role = null;
        public string CountryName = null;
    }
}
